Malkov. bd-2
dzinrai/koa-api-starter pull request #1
Opened 2020-07-24 08:40 UTC by dzinrai

2020-08-05 09:19 UTC, paralectvkomodey requested changes

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/add/index.js
> +  const results = await writerService.find({ _id: data.id });
Если ты хочешь найти один документ - то лучше использовать `findOne` - обойдешься от проверок на пустоту массива и взятия первого элемента. То есть код станет проще

Ещё хорошей практикой является присутствие метода `findById`. Пример можно найти в [документации](https://github.com/paralect/node-mongo/blob/master/API.md#setqueryservicemethodname-method)

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/add/index.js
> +  });
Не понятно, зачем делать `find`, а потом в `update` присваивать книжки. В твоём коде выходит 3 вызова в базу данных с кучей проверок. Всё это очень легко заменяется единственным оператором `$push` в mongodb и атомарным методом `update`

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/add/index.js
> +  _id: Joi.string().required(),
То что ты заставляешь пользователя генерировать `id` самому ручками - не самая хорошая затея. Таким образом ты говоришь, что пользователь ответственен за уникальность `id` ключа и сам это никак не проверяешь. Приложение, по-видимому, не будет корректно работать, если пользователь добавит 2 книжки с одинаковым ключём

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/remove/index.js
> +  });
Эти манипуляции можно делать в функции callback метода update. Не забывай, что внутри неатомарного `update` уже происходит `find`

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/remove/index.js
> +    return item.id === bookID || item._id === bookID;
Не совсем понятно, почему в `item` может быть 2 типа `id`. Давай сделаем, чтобы был только один `id`

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/books/rewrite/index.js
> +    doc.books = newBookList ? newBookList : [];
Используй атомарный `update`

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/create/index.js
> +}
А что валидирует этот валидатор? Я только вижу, что он изменяет входные данные

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/delete/index.js
> +  if (deletedWriter) ctx.body = deletedWriter;
Есть такое ощущение, что твой хэндлер ничего не вернет, если я в API прокину несуществующий id. Ты в любом случае должен что-то возвращать из API. И хорошо, если клиент поймет, в чём он совершил ошибку

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/get/index.js
> +  const dbqwe = await writerService.find({});
Отдавать ВСЕ записи из базы данных не является хорошей практикой. Представь - что у тебя там 2 ГБ писателей

Не совсем понятно, зачем нужен этот хэндлер

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/get/index.js
> +  const dbqwe = await writerService.find({});
Имя переменной - очень важный аспект в программировании. Впредь, не стоит водить котом по клаве, чтобы назвать переменную :)

Шутка(в которой есть доля шутки)

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/getByID/index.js
> +  ctx.body = dbqwe;
Опять. Клиент ожидает - что ему вернется одна запись, а ты возвращаешь массив. Используй findOne, если хочешь найти максимум одну запись

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/getMany/index.js
> +}
Представь, что у тебя в базе данных находится 2 ГБ писателей. В таком случае, ты достанешь их всех и начнёшь сортировать кодом

1. Это медленно - так как не используются никакие индексы
2. Ты наглухо забиваешь поток node.js и остальные клиенты должны ждать, пока кто-то не получит свой список

База данных оптимизирована под такие задачи. Код - нет. Приложение должно манипулировать маленькими кусочками данных, потому что вся память которая у него есть - оперативная и она довольно ограниченная(представь, что 30 клиентов одновременно попросят листинг авторов)

В методе `find` уже есть соответствующие аргументы для пагинации - используй их вместо сортировки и обрезания кодом

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/update/index.js
> +    if (data.books) doc.books = data.books;
Под эти цели есть атомарный метод update + оператор $set в MongoDB. Пожалуйста, перепиши код с их использованием

2020-08-05 09:19 UTC, paralectvkomodey commented on src/resources/writer/writer.schema.js
> +  _id: Joi.string() | Joi.object(),
id должен быть required. И не совсем понятно, почему у тебя тут стоит оператор `|`. Можешь пояснить?

2020-08-06 08:22 UTC, dzinrai commented on src/resources/writer/writer.schema.js
> +  _id: Joi.string() | Joi.object(),
думал там может быть какой-то обьект id и это где-то было в доке что ли, хз

2020-08-06 13:43 UTC, paralectvkomodey requested changes

2020-08-06 13:43 UTC, paralectvkomodey commented on src/resources/writer/books/add/index.js
> -  _id: Joi.string().required(),
я не уверен, что node-mongo будет автоматически генерировать `_id` в массивах, если ты его не укажешь. Проверь, пожалуйста

2020-08-06 13:43 UTC, paralectvkomodey commented on src/resources/writer/books/remove/index.js
> +    _.remove(books, function(item) {
лучше используй атомарный метод и оператор $pull

2020-08-06 13:43 UTC, paralectvkomodey commented on src/resources/writer/get/index.js
> +  const testFullDb = await writerService.find({});
Вообще говоря, это плохая практика, возвращать ВСЕ данные клиенту. Представь, что в базе у тебя 2ГБ. Это же не торренты. Всегда лимитируй выдачу. Если нужно больше чем лимит - создай функцию, которая будет уметь рекурсивно доставать нужное количество документов и обрабатывать их постранично

А в этом задании данный хэндлер не нужен

2020-08-10 09:29 UTC, merged